### ISSUE TITLE
Bug in Widget

### ISSUE THREAD

**Issue by kingfisher77** [PiBa-NL/pfsense-haproxy-package-doc#18]
We do experience this bug when we use the HAProxy widget

HAPRoxy Extension Version: [0.61_9]
pfsense: 23.01-RELEASE 

```
Crash report begins.  Anonymous machine information:

amd64
14.0-CURRENT
FreeBSD 14.0-CURRENT #0 plus-RELENG_23_01-n256037-6e914874a5e: Fri Feb 10 20:30:29 UTC 2023     root@freebsd:/var/jenkins/workspace/pfSense-Plus-snapshots-23_01-main/obj/amd64/VDZvZksF/var/jenkins/workspace/pfSense-Plus-snapshots-23_01-main/sources/FreeBS

Crash report details:

PHP Errors:
[30-Mar-2023 12:02:11 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string / int in /etc/inc/util.inc:2126
Stack trace:
#0 /usr/local/www/widgets/widgets/haproxy.widget.php(218): format_bytes('<NEVER>')
#1 /usr/local/www/index.php(430): include('/usr/local/www/...')
#2 {main}
  thrown in /etc/inc/util.inc on line 2126
[30-Mar-2023 12:02:29 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string / int in /etc/inc/util.inc:2126
Stack trace:
#0 /usr/local/www/widgets/widgets/haproxy.widget.php(218): format_bytes('<NEVER>')
#1 /usr/local/www/index.php(430): include('/usr/local/www/...')
#2 {main}
  thrown in /etc/inc/util.inc on line 2126


No FreeBSD crash data found.
```

**Comment by kingfisher77** [comment]
The bug renders the dashboard in an unusable status. Removing haproxy.widget.php solves the situation.

**Comment by stefb69** [comment]
Yeah I have the same problem, with pfsense+, will there be a fix for that or is it bc of something else and can be fixed ?
